source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'APValidators_Example', :exclusive => true do

end

target 'APValidators_Tests', :exclusive => true do
	pod 'Expecta'
	pod 'OCMock'
  
end
